#!/bin/zsh

CHAN=$1
source ~/.twitch_secrets;

rm -f /tmp/twitch_tunnel;
mkfifo /tmp/twitch_tunnel;

parsechat() {
    name=$(echo -n "$1" | grep -oP "display-name=.*?;" | cut -d'=' -f2- | tr -d ';\n')
    if [[ "$name" == "badcop_" ]]; then
        return
    fi
    msg=$(echo -n "$1" | grep -oP "PRIVMSG.*$" | cut -d':' -f2- | tr '[:upper:]' '[:lower:]')
    if [[ "$1" == *"custom-reward-id="* ]]; then
        x=$(echo "$msg" | grep -oE '(x|X)[0-9]+' | grep -oE '[0-9]+')
        y=$(echo "$msg" | grep -oE '(y|Y)[0-9]+' | grep -oE '[0-9]+')

        re='^[0-9]+$'
        if ! [[ $x =~ $re ]] ; then
            return
        fi
        if ! [[ $y =~ $re ]] ; then
            return
        fi

        pixel=$(./get-pixel "$x" "$y")
        if [[ "$pixel" == "00000000" ]]; then
            return
        fi
        pixel=$(echo "$pixel" | cut -c -6 | tr '[:upper:]' '[:lower:]')
        echo "$pixel"
        if echo "$msg" | grep -v "c$pixel"; then
            ./paint-pixel x${x}y${y}c${pixel} &
        fi
    fi
}
reqreader() {
  while IFS= read -r line; do
    [[ $line == "PING"* ]] && echo "PONG :tmi.twitch.tv\r";
    [[ "$line" == *" PRIVMSG "* ]] && (parsechat "$line" 1>&2)
  done;
  exit 0;
}
(echo "CAP REQ :twitch.tv/tags twitch.tv/commands\r\nPASS oauth:${TWITCH_ACCESS_TOKEN}\r\nNICK badcop_\r\nJOIN #${CHAN}\r"; \
    </tmp/twitch_tunnel | reqreader) \
    | websocat_linux64 wss://irc-ws.chat.twitch.tv:443 \
    | >/tmp/twitch_tunnel
