#!/bin/bash

x_offset=$(echo "$1" | sed 's/^0*//')
y_offset=$(echo "$2" | sed 's/^0*//')

x=$((x_offset-0))
y=$((y_offset-32))

echo "X: $x_offset, Y: $y_offset" >&2
echo "X: $x, Y: $y" >&2
echo >&2
if [[ "$x" == "-"* ]]; then
    echo "00000000"
    exit 0
fi
if [[ "$y" == "-"* ]]; then
    echo "00000000"
    exit 0
fi

convert ./diamond_trail.png -format '%[hex:u.p{'${x}','${y}'}]' info:-
